monolog:
    handlers:
        # this "file_log" key could be anything
        file_log:
            type: stream
            # log to var/log/(environment).log
            path: "php://stderr"
            # log *all* messages (debug is lowest level)
            level: debug
